sylabs/sif

README.md
Replace `godoc` link with `pkg.go.dev`, as the former has been deprecated ([ref](https://blog.golang.org/godoc.org-redirect)). Update CI badges/links with `sylabs` org.
=> Update CI Badges/Links

.circleci/config.yml, go.mod
Bump Go language version to 1.15 as per the stated [Go version compatibility](https://github.com/sylabs/sif#go-version-compatibility). Use latest Go version (1.16) in CI.
=> Update Go Version

go.mod, go.sum, internal/app/siftool/modif.go, pkg/integrity/testdata/gen_sifs.go, pkg/sif/create_test.go
As pointed out in https://github.com/sylabs/sif/issues/7#issuecomment-833889421, the latest tagged version of `github.com/satori/go.uuid` (1.2.0) contains the deficiency described in https://github.com/satori/go.uuid/issues/73.
Ultimately, we need to move to a maintained UUID Go module as described in https://github.com/sylabs/sif/issues/7#issuecomment-832808170. But this will necessitate a major version bump, and we may want to consider other breaking changes while we're at that.
In the meantime, advancing `github.com/satori/go.uuid` to the commit on `master` where this issue was addressed (https://github.com/satori/go.uuid/commit/75cca531ea763666bc46e531da3b4c3b95f64557).
=> Bump github.com/satori/go.uuid Module

.circleci/config.yml
Update `golangci-lint` to 1.40.x.
=> Bump golangci-lint to 1.40

.circleci/config.yml, .golangci.yml, internal/app/siftool/modif.go, pkg/sif/create.go
Update Codecov Orb to latest version. Use consistent naming convention (hyphens) in CI config. Replace deprecated `golint` linter with `revive`. Address lint found by `revive` linter.
=> CI Improvements

pkg/integrity/select.go, pkg/integrity/verify.go, pkg/sif/load.go, pkg/sif/load_test.go, pkg/sif/lookup.go, pkg/sif/lookup_test.go, pkg/sif/sif.go
Address occasional `SIGBUS` when accessing SIF file stored on a non-local filesystem by removing `mmap` usage.
Clarify `GetData` behaviour on error. Replace `GetData` usage with `GetReadSeeker` in `integrity` package.
Fixes #11
=> Remove mmap Usage

pkg/integrity/metadata.go, pkg/integrity/select.go, pkg/integrity/verify.go, pkg/sif/lookup.go, pkg/sif/lookup_test.go
Add `GetReader` and deprecate `GetReadSeeker`. Replace usage of `GetReadSeeker` with `GetReader` in `integrity` package.
Closes #14
=> Add GetReader

go.mod, go.sum, pkg/integrity/clearsign_test.go, pkg/integrity/digest_test.go, pkg/integrity/main_test.go, pkg/integrity/metadata_test.go, pkg/integrity/sign_test.go
Use [sebdah/goldie](https://pkg.go.dev/github.com/sebdah/goldie/v2) for golden file testing.
Closes #19
=> Use sebdah/goldie for Golden File Testing

internal/app/siftool/info.go, pkg/sif/fmt.go, pkg/sif/fmt_test.go, pkg/sif/sif.go, pkg/sif/testdata/TestFileImage_FmtDescrInfo/One.golden, pkg/sif/testdata/TestFileImage_FmtDescrInfo/Three.golden, pkg/sif/testdata/TestFileImage_FmtDescrInfo/Two.golden, pkg/sif/testdata/TestFileImage_FmtDescrList/output.golden, pkg/sif/testdata/TestFileImage_FmtHeader/output.golden
Deprecate [`FmtDescrInfo`](https://pkg.go.dev/github.com/sylabs/sif@v1.3.0/pkg/sif#FileImage.FmtDescrInfo), [`FmtDescrList`](https://pkg.go.dev/github.com/sylabs/sif@v1.3.0/pkg/sif#FileImage.FmtDescrList), and [`FmtHeader`](https://pkg.go.dev/github.com/sylabs/sif@v1.3.0/pkg/sif#FileImage.FmtHeader) in preparation for removal from v2 API (#22).
Expose `func String()` for `Fstype`, `Parttype`, `Hashtype`, `Formattype`, `Messagetype` types. Use `goldie` in formatting unit tests.
=> Deprecate Formatting Functions

cmd/siftool/info.go, cmd/siftool/modif.go, cmd/siftool/siftool.go, internal/app/siftool/file.go, internal/app/siftool/info.go, internal/app/siftool/modif.go, pkg/siftool/add.go, pkg/siftool/del.go, pkg/siftool/dump.go, pkg/siftool/info.go, pkg/siftool/setprim.go
Simplify code in `internal/app/siftool` package by removing unnecessary type casts and iterations on `DescrArr`. Move flag validation code to CLI packages.
=> Refactor siftool Package

LICENSE.md, README.md, cmd/siftool/siftool.go, go.mod, internal/app/siftool/file.go, internal/app/siftool/info.go, internal/app/siftool/modif.go, pkg/integrity/digest.go, pkg/integrity/digest_test.go, pkg/integrity/metadata.go, pkg/integrity/metadata_test.go, pkg/integrity/result.go, pkg/integrity/select.go, pkg/integrity/sign.go, pkg/integrity/sign_test.go, pkg/integrity/testdata/gen_sifs.go, pkg/integrity/verify.go, pkg/integrity/verify_test.go, pkg/siftool/add.go, pkg/siftool/del.go, pkg/siftool/dump.go, pkg/siftool/header.go, pkg/siftool/info.go, pkg/siftool/list.go, pkg/siftool/new.go, pkg/siftool/setprim.go
In preparation for version 2.0, update import path to `github.com/sylabs/sif/v2`.
Note: a [`v1` branch](https://github.com/sylabs/sif/tree/v1) has been created for ongoing 1.x maintenance. Development of version 2.x will occur on the `master` branch.
=> Bump Module Version to v2

cmd/siftool/siftool.go, internal/app/siftool/app.go, internal/app/siftool/info.go, internal/app/siftool/modif.go, pkg/siftool/add.go, pkg/siftool/del.go, pkg/siftool/dump.go, pkg/siftool/header.go, pkg/siftool/info.go, pkg/siftool/list.go, pkg/siftool/new.go, pkg/siftool/setprim.go, pkg/siftool/siftool.go
Reduce `github.com/sylabs/sif/v2/pkg/siftool` API surface. Add functional options in `github.com/sylabs/sif/v2/internal/app/siftool` package, and add `OptAppOutput` in  to support writing unit tests (#38).
Closes #39
=> Reduce Siftool API Surface

pkg/integrity/select.go, pkg/integrity/verify.go, pkg/sif/lookup.go, pkg/sif/lookup_test.go
Modify `GetData` to return `error`. Use `GetData` where appropriate to simplify code.
Closes #13
=> Modify GetData to Return Error

cmd/siftool/siftool.go, pkg/siftool/add.go, pkg/siftool/del.go, pkg/siftool/dump.go, pkg/siftool/header.go, pkg/siftool/info.go, pkg/siftool/list.go, pkg/siftool/new.go, pkg/siftool/setprim.go, pkg/siftool/siftool.go, pkg/siftool/siftool_test.go, pkg/siftool/testdata/TestAddCommands/Add/out.golden, pkg/siftool/testdata/TestAddCommands/Del/out.golden, pkg/siftool/testdata/TestAddCommands/Dump/out.golden, pkg/siftool/testdata/TestAddCommands/Header/out.golden, pkg/siftool/testdata/TestAddCommands/Info/out.golden, pkg/siftool/testdata/TestAddCommands/List/out.golden, pkg/siftool/testdata/TestAddCommands/New/out.golden, pkg/siftool/testdata/TestAddCommands/SetPrim/out.golden, pkg/siftool/testdata/TestAddCommands/SifTool/out.golden
Improve `siftool` documentation by adding `Long` descriptions (used unconditionally by `singularity`), and improving consistency of terminology across commands.
=> Improve Documentation

.github/dependabot.yml
The `v1` branch tracks maintenance of the 1.x.x major version, and should receive dependency updates.
=> Enable Dependabot on v1 Branch

cmd/siftool/siftool.go, internal/app/siftool/modif.go, pkg/integrity/testdata/gen_sifs.go, pkg/sif/create.go, pkg/sif/create_test.go, pkg/sif/load.go, pkg/sif/load_test.go, pkg/sif/lookup.go, pkg/sif/lookup_test.go, pkg/sif/sif.go, pkg/sif/sif_test.go
Use functional arguments for `CreateContainer`. Define `SpecVersion` type. Switch several header `const` values to be non-exported.
Closes #28
=> Functional Arguments for CreateContainer

pkg/sif/create.go, pkg/sif/create_test.go, pkg/sif/load.go, pkg/sif/lookup.go, pkg/sif/lookup_test.go, pkg/sif/sif.go, pkg/sif/sif_test.go
Make `Header` type un-exported, and remove `GetHeader`.
=> Make Header type Un-Exported

pkg/sif/fmt.go, pkg/sif/sif.go, pkg/sif/testdata/TestFileImage_FmtDescrInfo/One.golden, pkg/sif/testdata/TestFileImage_FmtDescrInfo/Three.golden, pkg/sif/testdata/TestFileImage_FmtDescrInfo/Two.golden
Mark `UID`/`Gid` fields deprecated in `type Descriptor struct` (see #59). Remove UID/GID values from `info` command output.
=> Deprecate Descriptor UID/Gid (V1)

pkg/sif/create.go, pkg/sif/create_test.go, pkg/sif/fmt.go, pkg/sif/load.go, pkg/sif/lookup.go
Re-name `CreateOpt` functions to use the same pattern as the `integrity` package. Use consistent receiver for `*FileImage` methods.
=> Consistency Fixups

internal/app/siftool/modif.go, pkg/integrity/testdata/gen_sifs.go, pkg/sif/create.go, pkg/sif/create_test.go
Do not close `Fp` in `CreateContainer`, so that `fimg` is usable by caller. Ensure internal calls to `CreateContainer` are mirrored with `UnloadContainer` (#67).
=> Return Usable FileImage from CreateContainer (v2)

internal/app/siftool/modif.go, internal/app/siftool/modif_test.go, pkg/integrity/digest.go, pkg/integrity/digest_test.go, pkg/integrity/sign.go, pkg/integrity/sign_test.go, pkg/sif/create.go, pkg/sif/create_test.go, pkg/sif/descriptor.go, pkg/sif/descriptor_input.go, pkg/sif/descriptor_input_test.go, pkg/sif/descriptor_test.go, pkg/sif/load.go, pkg/sif/select.go, pkg/sif/select_test.go, pkg/sif/sif.go, pkg/siftool/add.go
Use struct wrapping for `type Descriptor` to make internals non-exported. Use CamelCase for exported `type`s.
=> Wrap Descriptor and Use Consistent Case for Types

pkg/sif/create.go, pkg/sif/create_test.go, pkg/sif/descriptor.go, pkg/sif/descriptor_input.go, pkg/sif/load.go, pkg/sif/load_test.go, pkg/sif/select.go, pkg/sif/select_test.go, pkg/sif/sif.go
Simplify `ReadWriter interface` by removing the following:
- `io.Reader`: unused, code uses `io.ReaderAt` intstead.
- `io.Closer`: previously used in `UnloadContainer`. `LoadContainerReader` supports loading from a type that does not implement `Close`, for which conditional logic is necessary. Given this, we instead dynamically check if the underlying `ReadWriter` implements `io.Closer`, simplifying both the implementation as well as the exported interface.
- `Name`: unused, replaced with `OptObjectName`, which allows a user to explicitly pass a name.
- `Fd`: unused.
- `Stat`: previously used to obtain file size. We now use `Seek` to obtain file size.
- `Sync`:  `LoadContainerReader` supports loading from a type that does not implement `Sync`, for which conditional logic is necessary. In …
=> Simplify ReadWriter

internal/app/siftool/file.go, pkg/integrity/metadata_test.go, pkg/integrity/sign_test.go, pkg/integrity/verify_test.go, pkg/sif/create.go, pkg/sif/create_test.go, pkg/sif/descriptor_test.go, pkg/sif/load.go, pkg/sif/load_test.go
Consolidate `LoadContainer`, `LoadContainerFp`, and `LoadContainerReader` into `LoadContainer` and `LoadContainerFromPath`. Implement functional options for load `func`s. Normalize load func return type to be a pointer (`*FileImage`) to match method receivers.
Closes #77
=> Consolidate Load Funcs

pkg/sif/create.go, pkg/sif/descriptor.go, pkg/sif/descriptor_input.go, pkg/sif/descriptor_test.go, pkg/sif/select_test.go, pkg/sif/sif.go
Clean up package comment, and don't export unnecessary `const`s.
=> Small Clean Up

internal/app/siftool/info.go, internal/app/siftool/info_test.go, pkg/integrity/metadata.go, pkg/integrity/result.go, pkg/integrity/select.go, pkg/integrity/sign.go, pkg/integrity/sign_test.go, pkg/integrity/verify.go, pkg/sif/create.go, pkg/sif/create_test.go, pkg/sif/descriptor.go, pkg/sif/descriptor_test.go, pkg/sif/load.go, pkg/sif/select.go, pkg/sif/select_test.go, pkg/sif/sif.go
Hide `Descriptor` internals. Update names and types to improve consistency of v2 API.
Fixes #88
=> Hide rawDescriptor Internals

internal/app/siftool/info.go, pkg/integrity/metadata.go, pkg/integrity/select.go, pkg/integrity/sign_test.go, pkg/integrity/verify.go, pkg/sif/descriptor.go, pkg/sif/descriptor_test.go, pkg/sif/select.go
Add `io.ReaderAt` to `Descriptor` to simplify usage, removing `*FileImage` parameter.
Closes #91
=> Simplify GetData and GetReader

pkg/integrity/metadata.go, pkg/sif/create.go, pkg/sif/create_test.go, pkg/sif/descriptor.go, pkg/sif/descriptor_test.go, pkg/sif/load.go, pkg/sif/select.go, pkg/sif/select_test.go, pkg/sif/sif.go
Remove `relativeID` param from `(Descriptor).GetIntegrityReader` to simplify usage. Remove `primPartID` from `FileImage`.
=> Simplify Integrity Reader

pkg/sif/create.go, pkg/sif/create_test.go
Add functional options for `AddObject` and `SetPrimPart`. Add options to override creation/modification times.
Closes #85 , closes #86
=> Functional Options for AddObject and SetPrimPart

.circleci/config.yml, .goreleaser.yml
Add GoReleaser config. Add `release-test` job to `build_and_test` workflow. Add `tagged-release` workflow, with `publish-release` job. Rename `build_and_test` workflow to `build-and-test` for consistency.
Closes #99
=> Release with GoReleaser

pkg/integrity/metadata.go, pkg/integrity/result.go, pkg/integrity/verify.go, pkg/integrity/verify_test.go
Simplify `VerifyResult interface`. Return `type sif.Descriptor` from `Signature()` and `Verified()`, and remove `Signed()`.
Closes #107
=> Integrity descriptors

.circleci/config.yml, pkg/sif/create_test.go
Always test against latest two versions of Go in CI (#115). Replace usage of Go 1.16 `func`s in unit tests. Re-order jobs to simplify comparisons against `master`.
=> Test Against Latest Major Versions of Go (v1)

pkg/sif/create.go, pkg/sif/create_test.go, pkg/sif/load.go, pkg/sif/load_test.go, pkg/sif/sif.go
Add `OptCreateWithCloseOnUnload` and `OptLoadWithCloseOnUnload`, which allows the caller to specify whether the supplied `ReadWriter` should be closed when `UnloadContainer` is called. Improve unit tests for `LoadContainerFromPath` and `LoadContainer`.
=> Add OptCloseOnUnload

.circleci/config.yml, go.mod, pkg/integrity/main_test.go, pkg/sif/create_test.go, pkg/sif/load_test.go
Bump `go.mod` language version to 1.17 to take advantage of [lazy loading](https://golang.org/ref/mod#lazy-loading). Bump CI Go version range to 1.16-1.17. Remove use of deprecated `ioutil` package.
=> Bump Go to 1.17 (v1)

.circleci/config.yml, go.mod, go.sum, internal/app/siftool/modif_test.go, pkg/integrity/main_test.go, pkg/integrity/metadata_test.go, pkg/integrity/sign_test.go, pkg/sif/create_test.go, pkg/sif/load_test.go, pkg/siftool/new_test.go, pkg/siftool/siftool_test.go
Bump `go.mod` language version to 1.17 to take advantage of [lazy loading](https://golang.org/ref/mod#lazy-loading). Bump CI Go version range to 1.16-1.17. Remove use of deprecated `ioutil` package.
=> Bump Go to 1.17 (v2)

.circleci/config.yml, .golangci.yml
Bump `golangci-lint` to 1.42. Enable `errname` linter.
=> Bump Linter to 1.42 (v1)

.circleci/config.yml, .golangci.yml
Bump `golangci-lint` to 1.42. Enable `errname` linter.
=> Bump Linter to 1.42 (v2)

pkg/integrity/result.go, pkg/integrity/verify.go
Replace `VerifyResult interface` with a concrete type, to ease future expansion of the Verify API. This has a nice side-effect of unifying the results logic between the three `verifyTask` implementations. 
Closes #121
=> Use Concrete Types in VerifyCallback

pkg/integrity/sign_test.go, pkg/integrity/verify_test.go, pkg/sif/create.go, pkg/sif/select.go, pkg/sif/select_test.go
When `GetDescriptor`/`GetDescriptors` is called on an image with no descriptors, the returned error can be confusing. For example, when a `DescriptorSelectorFunc` is used with an invalid argument against an image with no descriptors, `ErrObjectNotFound` would be returned. `ErrNoObjects` allows the caller to differentiate this case, and display a more descriptive error.
=> ErrNoObjects from GetDescriptor(s)

git.go, mage.go, magefile.go, version.go
Add `//go:build` format build constraints [introduced in Go 1.17](https://golang.org/doc/go1.17#build-lines). Keep `// +build` format build constraints during the format transition.
=> Add New Format Build Constraints

pkg/integrity/sign.go, pkg/integrity/sign_test.go, pkg/integrity/verify.go, pkg/integrity/verify_test.go
Use `verifyOpts`/`signOpts` to accumulate options for `Verifier`/`Signer`.
=> Struct to Accumulate Integrity Options

pkg/integrity/result.go
Add missing documentation for `type VerifyResult`.
=> Document VerifyResult

pkg/sif/create.go, pkg/sif/sif.go
Correctly record `Storelen` for first object in new SIF images. Mark `const DataStartOffset` deprecated in place of the `Dataoff` field in the image header.
Fixes #139
=> Fix Inconsistent Alignment Accounting for Data Objects (v1)

pkg/sif/create.go, pkg/sif/create_test.go
Fix `nextAligned` to handle case where `alignment` is zero. Extend unit test to cover this case.
Closes #143
=> Fix OptObjectAlignment(0) Panic

internal/app/siftool/info.go, pkg/sif/descriptor.go, pkg/sif/descriptor_input.go, pkg/sif/sif.go
Return times in local timezone from `CreatedAt`/`ModifiedAt` methods. Continue using UTC to display dates in `siftool` command output.
Closes #138
=> Use "Local" Time Location

.golangci.yml, internal/pkg/git/git.go, pkg/sif/create.go, pkg/sif/descriptor_input.go, pkg/sif/load.go, pkg/sif/select.go, pkg/siftool/add.go, pkg/siftool/del.go, pkg/siftool/dump.go, pkg/siftool/info.go, pkg/siftool/setprim.go, test/gen_sifs.go
Use Go 1.13 wrapped errors. Enable `goerr113` linter to ease maintenance.
=> Use Wrapped Errors

cmd/siftool/modif.go, cmd/siftool/siftool.go, internal/app/siftool/file.go, internal/app/siftool/info.go, internal/app/siftool/modif.go, pkg/integrity/digest.go, pkg/integrity/digest_test.go, pkg/integrity/doc.go, pkg/integrity/metadata.go, pkg/integrity/metadata_test.go, pkg/integrity/result.go, pkg/integrity/select.go, pkg/integrity/sign.go, pkg/integrity/sign_test.go, pkg/integrity/verify.go, pkg/integrity/verify_test.go, pkg/sif/sif.go, pkg/siftool/add.go, pkg/siftool/siftool.go
Mark exported v1 packages as deprecated.
Closes #117
=> Deprecate v1 Packages

go.mod
Mark module deprecated using [module deprecation introduced in Go 1.17](https://golang.org/ref/mod#go-mod-file-module-deprecation).
Closes #117
=> Deprecate v1 Module

pkg/sif/descriptor_input.go
Fix `OptLinkedID` documentation to clarify it is used to specify a data object (not data object group).
=> Fix OptLinkedID Documentation

go.mod, go.sum
Bump `github.com/ProtonMail/go-crypto` from `v0.0.0-2021070 7164159-52430bf6b52c` to `v0.0.0-20210920160938-87db9fbc61c7`.
=> Bump github.com/ProtonMail/go-crypto

.goreleaser.yml, cmd/siftool/siftool.go, internal/pkg/git/git.go, magefile.go
Refactor `github.com/sylabs/sif/v2/internal/pkg/git` to expose `(*Description).CommitTime`. Remove `(*Description).Reference()` and add `(*Description).CommitHash()` in its place.
Ensure builds are reproducible by:
- Using `(*Description).CommitTime` as `main.date` for `mage` builds when the working directory is clean.
- Disabling CGO in `mage` builds.
- Use `-trimpath` in `mage`/`goreleaser` builds.
Harmonize linker flags used by `mage`/`goreleaser` by adding `-s -w` to `mage` build/install commands.
Use `Date:` rather than `Built:` in `siftool version` output to clarify semantics of this value (in clean builds, `main.date` is the commit date rather than the build date.
Closes #156
=> Reproducible Builds

.circleci/config.yml
Add `check-test-corpus`, which runs `test/gen_sifs.go` to generate the test corpus, and then verifies it hasn't changed.
=> Check Test Corpus Tidiness

.circleci/config.yml, .golangci.yml
Bump `golangci-lint` to v1.43 and enable `bidichk`, `contextcheck`, `ireturn`, `nilnil` and `tenv` linters.
=> Update golangci-lint and Enable New Linters

pkg/sif/create.go, pkg/sif/create_test.go
Improve error handling in `CreateContainerAtPath`. Extend unit test coverage for `CreateContainer` and `CreateContainerAtPath`.
Fixes #166
=> Fix Panic on Error in CreateContainerAtPath

magefile.go
Output `stdout` for `mage cover:unit`/`mage test:unit`.
=> Improve Output for Mage Commands

.circleci/config.yml, .golangci.yml, .goreleaser.yml, LICENSE.md
Bump `node` to v17, and `golangci-lint` to v1.44. Use correct types in `goreleaser` config.
=> CI Updates

.goreleaser.yml
Extend `goreleaser` configuration to build for all Linux architectures supported by `siftool`. Simplify `goreleaser` configuration, and split out `darwin` and `linux` builds separately.
=> Expand goreleaser Build Architectures

.circleci/config.yml, mage.go, magefile.go
Bump Go versions used in CI to 1.17 and 1.18. Remove deprecated build constraint format.
Closes #125
=> Adopt Go 1.18

.circleci/config.yml, .goreleaser.yml
=> sbom generating step

cmd/siftool/siftool.go, internal/app/siftool/app.go, internal/app/siftool/mount.go, internal/pkg/exp/mount.go, pkg/siftool/add_test.go, pkg/siftool/del_test.go, pkg/siftool/dump_test.go, pkg/siftool/header_test.go, pkg/siftool/info_test.go, pkg/siftool/list_test.go, pkg/siftool/mount.go, pkg/siftool/mount_test.go, pkg/siftool/new_test.go, pkg/siftool/setprim_test.go, pkg/siftool/siftool.go, pkg/siftool/siftool_test.go, pkg/siftool/testdata/TestAddCommands/Mount/out.golden, pkg/siftool/testdata/TestAddCommands/SifToolExperimental/out.golden, pkg/siftool/testdata/Test_command_getMount/Empty/err.golden, pkg/siftool/testdata/Test_command_getMount/Empty/out.golden
Add experimental `mount` command, which attempts to mount the primary system partition of a SIF image. At the moment, only SquashFS partitions are supported via `squashfuse`. Add `OptWithExperimental` to enable/disable hidden, experimental commands in `siftool`.
Closes #191
=> Experimental Mount Command

.goreleaser.yml
closes #202 
Fixed the sbom generating issue caused by missed part in the template.
=> ci: updated sbom name generating template

internal/app/siftool/unmount.go, internal/pkg/exp/unmount.go, internal/pkg/exp/unmount_test.go, pkg/siftool/siftool.go, pkg/siftool/unmount.go, pkg/siftool/unmount_test.go
Counterpart to mount, will unmount a squashfuse mounted filesystem via fusermount.
Fixes #205
=> feat: Add experimental unmount command

internal/app/siftool/mount.go, internal/app/siftool/unmount.go, pkg/sif/mount.go, pkg/sif/unmount.go, pkg/sif/unmount_test.go, pkg/siftool/unmount_test.go
Move `Mount` and `Unmount` to `pkg` from `internal`.
Rename to `xxxxFUSE` to make it clear these are FUSE mounts, rather than anything else.
Fixes https://github.com/sylabs/sif/issues/206
=> feat: expose MountFUSE / UnmountFUSE API

internal/app/siftool/mount.go, internal/app/siftool/unmount.go, pkg/siftool/unmount_test.go, pkg/user/mount.go, pkg/user/unmount.go, pkg/user/unmount_test.go
=> Move mount/unmount to user package

.circleci/config.yml, .golangci.yml, internal/app/siftool/file.go, pkg/integrity/select.go, pkg/sif/buffer.go, pkg/sif/descriptor.go
Bump `golangci-lint` to 1.46. Enable `nonamedreturns` and refactor/`nolint` as appropriate.
=> Bump golangci-lint

.circleci/config.yml, go.mod, go.sum, pkg/integrity/digest.go, pkg/integrity/doc.go, pkg/sif/descriptor.go, pkg/sif/sif.go
Test against Go 1.18 and 1.19 in CI. Bump module language version to 1.18. Reformat doc comments with `gofmt` from Go 1.19.
=> Go 1.19 Support

.circleci/config.yml, pkg/integrity/digest_test.go, pkg/integrity/verify.go
Bump `golangci-lint` to v1.48. Fix associated lint.
=> Bump Linter to 1.48

.circleci/config.yml, .golangci.yml
Disable deprecated `deadcode`, `structcheck` and `varcheck` linters. Add `interfacebloat` and `reassign` linters.
=> Bump golangci-lint to v1.49

.golangci.yml
Remove [rowserrcheck](https://github.com/jingyugao/rowserrcheck) linter, which is disabled by `golangci-lint` because it lacks support for generics.
=> ci: remove rowserrcheck linter

.circleci/config.yml
Explicitly check source code against the [Go Vulnerability Database](https://go.dev/security/vuln/database) during the `build-and-test` workflow.
=> ci: run govulncheck during build-and-test workflow

.circleci/config.yml, .golangci.yml, pkg/sif/create.go
Bump `golangci-lint` to v1.50. Enable `dupword` linter.
=> Bump golangci-lint to v1.50

pkg/integrity/clearsign.go, pkg/integrity/clearsign_test.go, pkg/integrity/select.go, pkg/integrity/sign.go, pkg/integrity/sign_test.go, pkg/integrity/verify.go, pkg/integrity/verify_test.go
De-couple digital signature decoding and verification from higher level verifier logic. Centralize fingerprint and vericiation callback logic. Re-factor `type encoder interface` to make fingerprint optional via `optSignGroupFingerprint`.
=> Refactor verifyTask

.circleci/config.yml, test/images/gen_sifs.go
Move `test/gen_sifs.go` to `test/images/` directory for consistency (ex. `test/keys/gen_keys.go`).
=> test: move gen_sifs.go to images dir

.circleci/config.yml, go.mod, go.sum, pkg/integrity/clearsign_test.go, pkg/integrity/sign_test.go
Bump module Go version to 1.19. Advance CI testing to Go 1.19-1.20. Bump `github.com/ProtonMail/go-crypto` to latest. Remove SHA1 test case, since signing with SHA1 is no longer supported by `go-crypto` (https://github.com/ProtonMail/go-crypto/pull/143).
=> Bump Go Version

pkg/integrity/digest.go, pkg/integrity/dsse.go
Temporarily disable `go-errorlint` where suggestions would break Go 1.19 compatibility (https://github.com/polyfloyd/go-errorlint/issues/37).
=> fix: add nolint to silence go-errorlint

pkg/integrity/clearsign.go, pkg/integrity/clearsign_test.go, pkg/integrity/dsse.go, pkg/integrity/dsse_test.go, pkg/integrity/sign.go, pkg/integrity/sign_test.go, pkg/integrity/verify.go, pkg/integrity/verify_test.go
Add `OptSignWithContext`/`OptVerifyWithContext`, which allow a `context.Context` to be supplied and used in `Sign`/`Verify`.
Fixes #258
=> Expose Context in Sign/Verify

.circleci/config.yml, .golangci.yml, pkg/integrity/clearsign.go, pkg/integrity/digest.go, pkg/integrity/dsse.go, pkg/integrity/verify_test.go, pkg/sif/create.go, pkg/siftool/siftool.go
Bump `golangci-lint` to v1.52. Replace individual `nolint` lines with `errorf-multi: false` in global CI config (#265). Re-enable `unused` linter (closes #269).
=> chore: bump golangci-lint to v1.52

.codecov.yml
These just started showing up, and are failing. Disabling for now.
=> ci: disable GitHub checks for CodeCov

.circleci/config.yml, .golangci.yml, pkg/integrity/dsse_test.go, pkg/sif/select_test.go, pkg/siftool/siftool_test.go
Disable `depguard`, enable `forcetypeassert`, `thelper` and new `mirror` linter.
=> ci: bump golangci-lint to v1.53

pkg/siftool/siftool_test.go
Restore previous behaviour for `makeTestSIF` on error.
=> test: report file/line info for makeTestSIF errors

.codecov.yml
Building on #296, disable Github status updates for now.
=> ci: disable codecov status

.circleci/config.yml
Start verifying compatibility with upcoming Go 1.21 release (https://go.dev/blog/go1.21rc).
=> test: add testing against Go 1.21 RC

internal/app/siftool/modif_test.go, pkg/sif/descriptor.go, pkg/siftool/add_test.go
Use `sha256.New()` rather than `crypto.SHA256.New()` to ensure the SHA256 algorithm is available (avoids "requested hash function is unavailable" panic in #313.) Improve tests for `add` of OCI index/blob.
Fixes #313
=> fix: ensure hash function is available

pkg/integrity/metadata.go, pkg/integrity/select.go, pkg/integrity/verify.go, pkg/sif/descriptor_input.go
As of v1.4.4, go-errorlint exempts `Is` methods from type assertions (see https://github.com/polyfloyd/go-errorlint/issues/50).
=> chore: remove unnecessary nolint:errorlint lines

pkg/sif/create.go
Replace `func zeroData` with a simpler implementation that uses an `io.Reader` that streams zero bytes.
=> refactor: simplify zero implementation

cmd/siftool/siftool.go, pkg/integrity/verify_test.go, pkg/sif/descriptor_input.go, pkg/siftool/del.go, pkg/siftool/dump.go, pkg/siftool/header.go, pkg/siftool/info.go, pkg/siftool/list.go, pkg/siftool/new.go, pkg/siftool/setprim.go
`revive` linter now checks for this as of v1.3.7.
=> fix: remove unused params in function literals

.circleci/config.yml
In advance of #351, start testing against Go 1.22 release.
=> ci: test against Go 1.22

.circleci/config.yml, .golangci.yml, internal/app/siftool/info_test.go, pkg/integrity/clearsign_test.go, pkg/integrity/digest_test.go, pkg/integrity/dsse_test.go, pkg/integrity/metadata_test.go, pkg/integrity/sign_test.go, pkg/integrity/verify_test.go, pkg/sif/descriptor_test.go, pkg/sif/load_test.go, pkg/sif/sif_test.go
Bump `golangci-lint` to v1.57. Add `copyloopvar` and `intrange`, which won't come into play until this module adopts Go 1.22 but play nicely with Go 1.21. Drop loop variable usage in (non-parallel) tests, which is safe for Go 1.21 and will lessen the number of changes required for a clean `copyloopvar` run when Go 1.22 is adopted.
Add patch version to `go` directive in `go.mod` (see https://github.com/golang/go/issues/62278).
=> chore: bump golangci-lint to v1.57

.circleci/config.yml, .golangci.yml, pkg/sif/descriptor_input_test.go
Bump `golangci-lint` to v1.59. Update linter config to reflect name change of linter `goerr113` to `err113`.
=> ci: bump golangci-lint to v1.59

.circleci/config.yml, .goreleaser.yml
Update configs to leverage Goreleaser v2.
=> ci: update to use goreleaser v2

.circleci/config.yml, go.mod
Start building/testing against `go1.23-rc` in CI. Add patch version to `go` directive to address `Invalid Go toolchain version` warning in CodeQL.
=> ci: add testing against Go 1.23 RC

.circleci/config.yml, go.mod
Bump module Go version to 1.22, and drop testing against Go 1.21. This should (finally) allow updating the `github.com/sigstore/sigstore` dependency.
=> chore: bump module to Go 1.22

.circleci/config.yml, .golangci.yml, pkg/sif/create.go, pkg/sif/create_test.go, pkg/siftool/del.go, pkg/siftool/dump.go, pkg/siftool/info.go, pkg/siftool/setprim.go
Bump `golangci-lint` to v1.60. Address lint, and remove deprecated linter.
=> chore: bump golangci-lint to v1.60

.circleci/config.yml, pkg/sif/create.go, pkg/siftool/del.go, pkg/siftool/dump.go, pkg/siftool/info.go, pkg/siftool/setprim.go
Remove some `nolint` comments that are no longer necessary due to improvements in the `gosec` linter. Improve alignment overflow check logic.
=> ci: bump golangci-lint to v1.61

.circleci/config.yml, .golangci.yml, pkg/integrity/verify.go
Fix `revive` lint (redefinition of the built-in type any), and add `iface` linter.
=> chore: bump `golangci-lint` to v1.62

.circleci/config.yml, .golangci.yml, internal/app/siftool/modif_test.go, pkg/sif/create_test.go, pkg/siftool/new_test.go, pkg/siftool/siftool_test.go, pkg/user/unmount_test.go
Enable `exptostd`, `nilnesserr` and `usetesting` linters.
=> lint: bump `golangci-lint` to v1.63

.circleci/config.yml, go.mod
Bump module Go version to 1.23, and drop testing against Go 1.22. Bump `golangci-lint` to v1.64 to ensure Go 1.24 compatibility.
=> chore: bump module to Go 1.23

.goreleaser.yml
As per https://goreleaser.com/deprecations/#archivesbuilds
=> fix: remove deprecated goreleaser config
